CREATE TABLE `dinner_shop` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '店名' COLLATE 'utf8_general_ci',
	`name_en` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '土味英文店名' COLLATE 'utf8_general_ci',
	`remark` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '备注' COLLATE 'utf8_general_ci',
	`status` INT(11) NOT NULL DEFAULT '1' COMMENT '状态',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='晚餐店铺'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=14
;


CREATE TABLE `dinner_user` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`ip` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'ip' COLLATE 'utf8_general_ci',
	`email` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '企业微信邮箱' COLLATE 'utf8_general_ci',
	`status` INT(11) NOT NULL DEFAULT '1',
	`name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '人名' COLLATE 'utf8_general_ci',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='晚餐用户'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=13
;


CREATE TABLE `dinner_vote` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`date` INT(11) NOT NULL DEFAULT '0' COMMENT '日期',
	`shop_id` INT(11) NOT NULL DEFAULT '0' COMMENT '店铺id',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	`status` INT(11) NOT NULL DEFAULT '0' COMMENT '1-中了',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='某天投票选项'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=7
;


CREATE TABLE `dinner_vote_log` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) NOT NULL DEFAULT '0' COMMENT '用户id',
	`shop_id` INT(11) NOT NULL DEFAULT '0' COMMENT '店铺id',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='晚餐投票日志'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=7
;
