CREATE TABLE `dinner_user` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`ip` VARCHAR(64) NOT NULL DEFAULT '0' COMMENT 'ip' COLLATE 'utf8_general_ci',
	`name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '人名' COLLATE 'utf8_general_ci',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='晚餐用户'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `dinner_shop` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '店名' COLLATE 'utf8_general_ci',
	`name_en` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '土味英文店名' COLLATE 'utf8_general_ci',
	`remark` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '备注' COLLATE 'utf8_general_ci',
	`STATUS` INT(11) NOT NULL DEFAULT '1' COMMENT '状态',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='晚餐店铺'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

REATE TABLE `dinner_vote` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) NOT NULL DEFAULT '0' COMMENT '用户id',
	`shop_id` INT(11) NOT NULL DEFAULT '0' COMMENT '店铺id',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='晚餐投票'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

